### ISSUE TITLE
Pre commit

### ISSUE THREAD

**Issue by Dorian30** [Zillacracy-org/ssibrowser.com#12]
I wanna add a pre commit script to run linters against staged git files in order to avoid errors slip into the code base (Like types error, for example).

**Comment by tralcanx** [comment]
great idea!!

**Comment by tralcanx** [comment]
PR merged - shall we close this issue or do you have further additions @Dorian30 ?

**Comment by Dorian30** [comment]
We can close it now. The script is all set and ready to go. Nothing more to do here.
